// <auto-generated />
namespace CinemaCommon.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AlterMoviePriceDataType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterMoviePriceDataType));
        
        string IMigrationMetadata.Id
        {
            get { return "201302271232492_AlterMoviePriceDataType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
